using UnityEngine;
namespace PharmaBrawl {
 public static class MedicalVfx {
  public static GameObject Quad(){var g=new GameObject("Pooled textured muzzle flash",typeof(MeshFilter),typeof(MeshRenderer));var mesh=new Mesh();mesh.vertices=new[]{new Vector3(-.5f,-.5f,0),new Vector3(.5f,-.5f,0),new Vector3(.5f,.5f,0),new Vector3(-.5f,.5f,0)};mesh.colors=new[]{Color.white,Color.white,Color.white,Color.white};mesh.uv=new[]{Vector2.zero,Vector2.right,Vector2.one,Vector2.up};mesh.triangles=new[]{0,2,1,0,3,2};mesh.RecalculateBounds();g.GetComponent<MeshFilter>().sharedMesh=mesh;g.GetComponent<Renderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;return g;}
  public static Material Material(int tile,bool smoke=false){var m=new Material(Resources.Load<Material>("VFX/MedicalVFX"));m.mainTexture=Resources.Load<Texture2D>("VFX/MedicalAtlas");m.mainTextureScale=Vector2.one*.5f;m.mainTextureOffset=new Vector2(tile%2*.5f,tile<2?.5f:0);m.SetFloat("_DstBlend",smoke?10:1);return m;}
  public static ParticleSystem Layer(GameObject parent,string name,Material material,float life,float size,float speed,int budget){var child=new GameObject(name);child.transform.SetParent(parent.transform,false);var ps=child.AddComponent<ParticleSystem>();var m=ps.main;m.playOnAwake=false;m.loop=false;m.maxParticles=budget;m.startLifetime=life;m.startSize=size;m.startSpeed=speed;m.simulationSpace=ParticleSystemSimulationSpace.World;var emission=ps.emission;emission.enabled=false;var shape=ps.shape;shape.shapeType=ParticleSystemShapeType.Sphere;shape.radius=.1f;var scale=ps.sizeOverLifetime;scale.enabled=true;scale.size=new ParticleSystem.MinMaxCurve(1,new AnimationCurve(new Keyframe(0,.3f),new Keyframe(.2f,1),new Keyframe(1,1.4f)));var color=ps.colorOverLifetime;color.enabled=true;var g=new Gradient();g.SetKeys(new[]{new GradientColorKey(Color.white,0),new GradientColorKey(Color.white,1)},new[]{new GradientAlphaKey(1,0),new GradientAlphaKey(.7f,.35f),new GradientAlphaKey(0,1)});color.color=g;var renderer=ps.GetComponent<ParticleSystemRenderer>();renderer.sharedMaterial=material;renderer.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;ps.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);return ps;}
 }
}

