using UnityEngine;
namespace PharmaBrawl
{
    // State presentation for shields, haste, artillery, poison, spread and blink.
    public sealed class ReferenceAbilityView:MonoBehaviour
    {
        sealed class ZoneView{public GameObject root;public LineRenderer ring;public ParticleSystem cloud;public Transform bomb;public float tick=-1,pulse;public bool active;}
        sealed class Burst{public GameObject root;public LineRenderer ring;public ParticleSystem sparks,flash,smoke;public float time,duration,radius;public int owner;public Vector3 position;public Color color;}
        readonly ZoneView[] zones=new ZoneView[48];readonly Burst[] bursts=new Burst[24];
        Transform[] shieldSurface;Material shieldMaterial;
        LineRenderer[] shield,slow,haste,fan,dash;float[] dashLife;Vector2[] dashStart,blinkStart;bool[] blinkPending;
        ArenaSimulation simulation;Material glow,smoke,impact;Texture2D softTexture;int cursor;bool visible=true;
        Transform[] actors;SkinnedMeshRenderer[] skins;Mesh[] ghostMeshes;Transform[,] ghosts;Vector3[] ghostOffset;Quaternion[] ghostRotation;Vector3[] ghostScale;
        public int ActiveZones{get{int n=0;foreach(var z in zones)if(z!=null&&z.active)n++;return n;}}
        static Vector3 P(Vector2 p,float y=.25f)=>new Vector3(p.x,y,p.y);
        public void Initialize(ArenaSimulation model,Transform[] actorViews=null){
            simulation=model;glow=new Material(Shader.Find("Sprites/Default"));softTexture=new Texture2D(32,32,TextureFormat.RGBA32,false);for(int x=0;x<32;x++)for(int y=0;y<32;y++){float r=new Vector2((x-15.5f)/15.5f,(y-15.5f)/15.5f).magnitude;softTexture.SetPixel(x,y,new Color(1,1,1,Mathf.Pow(Mathf.Clamp01(1-r),2)));}softTexture.Apply();smoke=MedicalVfx.Material(1,true);impact=MedicalVfx.Material(0);
            for(int i=0;i<zones.Length;i++){
                var root=new GameObject("Pooled authoritative area "+i);root.transform.SetParent(transform,false);var z=new ZoneView{root=root,ring=Line(root,"Exact zone damage boundary",65),cloud=Particles(root,"Expanding purple gas",true)};
                var bomb=Instantiate(Resources.Load<GameObject>("Projectiles/Capsule"),root.transform).transform;z.bomb=bomb;foreach(var c in bomb.GetComponentsInChildren<Collider>())Destroy(c);var b=PharmacistModelRig.BoundsOf(bomb);float scale=.9f/Mathf.Max(b.size.x,Mathf.Max(b.size.y,b.size.z));bomb.localScale=Vector3.one*scale;
                foreach(var renderer in bomb.GetComponentsInChildren<Renderer>()){var block=new MaterialPropertyBlock();block.SetColor("_Color",new Color(.15f,.55f,1));renderer.SetPropertyBlock(block);}var falling=bomb.gameObject.AddComponent<TrailRenderer>();falling.sharedMaterial=impact;falling.time=.2f;falling.startWidth=.24f;falling.endWidth=0;falling.startColor=new Color(.15f,.7f,1,.7f);falling.endColor=new Color(.15f,.7f,1,0);falling.minVertexDistance=.08f;falling.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;zones[i]=z;root.SetActive(false);
            }
            for(int i=0;i<bursts.Length;i++){var root=new GameObject("Pooled reference impact "+i);root.transform.SetParent(transform,false);bursts[i]=new Burst{root=root,ring=Line(root,"Short impact wave",49),sparks=Particles(root,"Impact sparks",false),flash=MedicalVfx.Layer(root,"Artillery hot core",impact,.14f,2,0,1),smoke=MedicalVfx.Layer(root,"Residual artillery smoke",smoke,.65f,1.5f,.7f,5)};root.SetActive(false);}
            int count=model.fighters.Length;shieldMaterial=new Material(Resources.Load<Material>("VFX/MedicalShield"));shieldSurface=new Transform[count];shield=new LineRenderer[count];slow=new LineRenderer[count];haste=new LineRenderer[count];fan=new LineRenderer[count];dash=new LineRenderer[count];dashLife=new float[count];dashStart=new Vector2[count];blinkStart=new Vector2[count];blinkPending=new bool[count];
            for(int i=0;i<count;i++){var bubble=GameObject.CreatePrimitive(PrimitiveType.Sphere);Destroy(bubble.GetComponent<Collider>());bubble.name="Pooled wrapping shield surface";bubble.transform.SetParent(transform,false);bubble.transform.localScale=Vector3.one*2.8f;bubble.GetComponent<Renderer>().sharedMaterial=shieldMaterial;shieldSurface[i]=bubble.transform;bubble.SetActive(false);shield[i]=Line(gameObject,"Cyan purple shield "+i,97);slow[i]=Line(gameObject,"Actual poison slow marker "+i,7);haste[i]=Line(gameObject,"Rapid fire energy "+i,33);fan[i]=Line(gameObject,"Empowered fan range "+i,35);dash[i]=Line(gameObject,"Actual dash path "+i,9);}
            actors=actorViews;skins=new SkinnedMeshRenderer[count];ghostMeshes=new Mesh[count];ghosts=new Transform[count,3];ghostOffset=new Vector3[count];ghostRotation=new Quaternion[count];ghostScale=new Vector3[count];
            if(actors!=null)for(int i=0;i<count;i++){skins[i]=actors[i].GetComponentInChildren<SkinnedMeshRenderer>();if(!skins[i])continue;ghostMeshes[i]=new Mesh();for(int j=0;j<3;j++){var ghost=new GameObject("Pooled actual character afterimage "+i+" "+j);ghost.transform.SetParent(transform,false);ghost.AddComponent<MeshFilter>().sharedMesh=ghostMeshes[i];var renderer=ghost.AddComponent<MeshRenderer>();renderer.sharedMaterial=glow;renderer.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;ghosts[i,j]=ghost.transform;ghost.SetActive(false);}}
        }
        void CaptureGhost(int id){if(actors==null||!skins[id])return;skins[id].BakeMesh(ghostMeshes[id]);ghostOffset[id]=skins[id].transform.position-actors[id].position;ghostRotation[id]=skins[id].transform.rotation;ghostScale[id]=skins[id].transform.lossyScale;}
        LineRenderer Line(GameObject root,string name,int points){var child=new GameObject(name);child.transform.SetParent(root.transform,false);var line=child.AddComponent<LineRenderer>();line.sharedMaterial=glow;line.positionCount=points;line.useWorldSpace=true;line.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;line.enabled=false;return line;}
        ParticleSystem Particles(GameObject root,string name,bool gas){var child=new GameObject(name);child.transform.SetParent(root.transform,false);var ps=child.AddComponent<ParticleSystem>();var m=ps.main;m.playOnAwake=false;m.loop=gas;m.maxParticles=gas?24:24;m.startLifetime=gas?1.1f:.35f;m.startSpeed=gas?.4f:5;m.startSize=gas?1.8f:.15f;m.simulationSpace=gas?ParticleSystemSimulationSpace.Local:ParticleSystemSimulationSpace.World;m.startColor=gas?new Color(.65f,.12f,1,.4f):Color.white;
            var emission=ps.emission;emission.enabled=gas;emission.rateOverTime=gas?18:0;var shape=ps.shape;shape.shapeType=gas?ParticleSystemShapeType.Circle:ParticleSystemShapeType.Sphere;shape.rotation=gas?new Vector3(90,0,0):Vector3.zero;shape.radius=gas?1:.1f;var size=ps.sizeOverLifetime;size.enabled=true;size.size=new ParticleSystem.MinMaxCurve(1,gas?AnimationCurve.Linear(0,.4f,1,1.4f):AnimationCurve.Linear(0,1,1,0));
            var colors=ps.colorOverLifetime;colors.enabled=true;var gradient=new Gradient();gradient.SetKeys(new[]{new GradientColorKey(Color.white,0),new GradientColorKey(Color.white,1)},new[]{new GradientAlphaKey(gas?0:1,0),new GradientAlphaKey(gas?.7f:1,.3f),new GradientAlphaKey(0,1)});colors.color=new ParticleSystem.MinMaxGradient(gradient);
            var renderer=ps.GetComponent<ParticleSystemRenderer>();renderer.sharedMaterial=gas?smoke:impact;renderer.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;ps.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);return ps;}
        static void Circle(LineRenderer line,Vector3 center,float radius,Color color,float width=.06f){line.enabled=false;}
        void BurstAt(Vector2 position,float radius,Color color,int owner,float duration=.45f,bool explosive=false){var b=bursts[cursor++%bursts.Length];b.sparks.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);b.flash.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);b.smoke.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);b.position=P(position,.3f);b.root.transform.position=b.position;b.radius=radius;b.color=color;b.owner=owner;b.duration=duration;b.time=duration;b.root.SetActive(true);var main=b.sparks.main;main.startColor=new ParticleSystem.MinMaxGradient(color,Color.white);main.startSpeed=radius>1?6:3;b.sparks.Emit(radius>1?16:8);if(explosive){var core=b.flash.main;core.startSize=radius*1.5f;core.startColor=new Color(1,.9f,.5f);b.flash.Emit(1);var mist=b.smoke.main;mist.startSize=radius*.7f;mist.startColor=new Color(.5f,.32f,.2f,.2f);b.smoke.Emit(4);}Draw(b);}
        void Draw(Burst b){float age=1-b.time/b.duration;var color=b.color;color.a=1-age;Circle(b.ring,b.position,b.radius*Mathf.Min(1,.2f+age*4),color,.12f*(1-age));}
        public void Emit(ArenaSimulation.CombatEvent e){if(!visible)return;var f=simulation.fighters[e.actor];
            if(e.type=="death"||e.type=="withdraw"){dashLife[e.actor]=0;blinkPending[e.actor]=false;foreach(var b in bursts)if(b.owner==e.actor){b.time=0;b.root.SetActive(false);}return;}
            if(e.type=="ultimate"&&f.data.kind==AttackKind.Wave){dashStart[e.actor]=e.position;dashLife[e.actor]=.5f;CaptureGhost(e.actor);}
            if(e.type=="blink"){BurstAt(e.position,.75f,new Color(1,.25f,.8f),e.actor);if(!blinkPending[e.actor]){blinkStart[e.actor]=e.position;blinkPending[e.actor]=true;CaptureGhost(e.actor);}else{dashStart[e.actor]=blinkStart[e.actor];dashLife[e.actor]=.4f;blinkPending[e.actor]=false;}return;}
            if(e.type=="robotDestroyed")BurstAt(e.position,e.size,new Color(1,.65f,.2f),e.actor,.6f,true);
            if(e.type=="explosion"&&f.data.kind==AttackKind.Artillery)BurstAt(e.position,e.size,new Color(1,.7f,.1f),e.actor,.75f,true);
            if(e.type=="wave")BurstAt(e.position,e.size,new Color(.75f,.2f,1),e.actor);
            if(e.type=="hit"){bool poisoned=f.poison>0;foreach(var z in simulation.zones)if(z.active&&!z.pending&&z.kind==2&&simulation.fighters[z.owner].team!=f.team&&Vector2.Distance(z.position,e.position)<z.radius)poisoned=true;if(poisoned)BurstAt(e.position,.45f,new Color(.85f,.2f,1),e.actor,.25f);else BurstAt(e.position,.28f,new Color(1,.92f,.7f),e.actor,.2f);}
        }
        public void Advance(float dt){if(!visible)return;
            for(int i=0;i<zones.Length;i++){var state=simulation.zones[i];var view=zones[i];bool active=state.active&&simulation.fighters[state.owner].data.kind!=AttackKind.Capsule;
                if(!active){if(view.active){view.cloud.Stop(true,ParticleSystemStopBehavior.StopEmitting);view.active=false;}view.bomb.gameObject.SetActive(false);view.ring.enabled=false;if(view.cloud.particleCount==0)view.root.SetActive(false);continue;}
                bool first=!view.active;view.active=true;view.root.SetActive(true);view.root.transform.position=P(state.position,0);var color=state.kind==2?new Color(.85f,.2f,1):new Color(.1f,.8f,1);
                if(first){view.tick=-1;if(state.kind==2){var shape=view.cloud.shape;shape.radius=state.radius*.85f;var main=view.cloud.main;main.startSize=state.radius*.65f;view.cloud.Play();view.cloud.Emit(6);}}
                bool damagePulse=view.tick>=0&&state.tick>view.tick+.1f;if(damagePulse)view.pulse=.18f;view.tick=state.tick;view.pulse=Mathf.Max(0,view.pulse-dt);color.a=.7f;Circle(view.ring,P(state.position),state.radius,color,.06f+view.pulse*.2f);
                view.bomb.gameObject.SetActive(state.pending);if(state.pending){view.bomb.localPosition=Vector3.up*(1+Mathf.Clamp01(state.remaining/1.5f)*7);view.bomb.localRotation=Quaternion.Euler(0,Time.time*90,0);}
                if(state.kind==1&&damagePulse)BurstAt(state.position,state.radius,new Color(.1f,.65f,1),state.owner,.2f);
            }
            foreach(var b in bursts)if(b.time>0){b.time=Mathf.Max(0,b.time-dt);if(b.time==0){b.root.SetActive(false);b.sparks.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);}else Draw(b);}
            for(int i=0;i<simulation.fighters.Length;i++){var f=simulation.fighters[i];Vector3 center=P(f.position,1.4f);bool alive=f.Alive;
                shield[i].enabled=alive&&f.data.kind==AttackKind.Wave&&f.shield>0;shieldSurface[i].gameObject.SetActive(shield[i].enabled);shieldSurface[i].position=center;if(shield[i].enabled){var line=shield[i];line.startColor=line.endColor=new Color(.3f,.8f,1,.65f);line.widthMultiplier=.045f;for(int j=0;j<97;j++){float angle=j*Mathf.PI*2/32;int axis=Mathf.Min(2,j/33);Vector3 p=axis==0?new Vector3(Mathf.Cos(angle),Mathf.Sin(angle),0):axis==1?new Vector3(0,Mathf.Cos(angle),Mathf.Sin(angle)):new Vector3(Mathf.Cos(angle),0,Mathf.Sin(angle));line.SetPosition(j,center+p*1.4f);}}
                bool slowed=false;foreach(var z in simulation.zones)if(z.active&&!z.pending&&z.kind==2&&simulation.fighters[z.owner].team!=f.team&&Vector2.Distance(z.position,f.position)<z.radius)slowed=true;
                slow[i].enabled=false;if(slow[i].enabled){var line=slow[i];line.widthMultiplier=.07f;line.startColor=line.endColor=new Color(.9f,.3f,1);Vector3 top=center+Vector3.up*1.5f;Vector3[] offsets={Vector3.zero,Vector3.down*.7f,new Vector3(-.2f,-.45f,0),Vector3.down*.7f,new Vector3(.2f,-.45f,0),Vector3.down*.7f,Vector3.zero};for(int j=0;j<7;j++)line.SetPosition(j,top+offsets[j]);}
                haste[i].enabled=alive&&f.data.kind==AttackKind.Burst&&f.haste>0;if(haste[i].enabled)Circle(haste[i],P(f.position,.3f),.7f,new Color(.7f,1,.15f,.7f),f.rapidRemaining>0?.12f:.055f);
                fan[i].enabled=false;if(fan[i].enabled){var line=fan[i];line.startColor=line.endColor=new Color(.15f,.8f,1,.45f);line.widthMultiplier=.035f;for(int j=0;j<35;j++){Vector2 p=j==0||j==34?f.position:f.position+ArenaSimulation.Rotate(f.aim,Mathf.Lerp(-32,32,(j-1)/32f))*f.data.range*1.4f;line.SetPosition(j,P(p,.23f));}}
                dashLife[i]=Mathf.Max(0,dashLife[i]-dt);dash[i].enabled=alive&&dashLife[i]>0;if(dash[i].enabled){dash[i].startColor=dash[i].endColor=new Color(.85f,.2f,1,dashLife[i]);dash[i].widthMultiplier=.28f;for(int j=0;j<9;j++)dash[i].SetPosition(j,P(Vector2.Lerp(dashStart[i],f.position,j/8f),.8f));}
                shield[i].enabled=false;dash[i].enabled=false;
                for(int j=0;j<3;j++)if(ghosts[i,j]){var ghost=ghosts[i,j];ghost.gameObject.SetActive(alive&&dashLife[i]>0);if(!alive||dashLife[i]<=0)continue;ghost.position=P(Vector2.Lerp(dashStart[i],f.position,j/3f),0)+ghostOffset[i];ghost.rotation=ghostRotation[i];ghost.localScale=ghostScale[i];var block=new MaterialPropertyBlock();block.SetColor("_Color",new Color(1,.3f,.9f,dashLife[i]*.5f));ghost.GetComponent<Renderer>().SetPropertyBlock(block);}
            }
        }
        void Update(){Advance(Time.deltaTime);}public void SetVisible(bool value){if(visible==value)return;if(!value)Clear();else visible=true;}
        public void Clear(){visible=false;foreach(var z in zones)if(z!=null){z.active=false;z.root.SetActive(false);z.cloud.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);}foreach(var b in bursts)if(b!=null){b.time=0;b.root.SetActive(false);b.sparks.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);}if(shield!=null)for(int i=0;i<shield.Length;i++){shieldSurface[i].gameObject.SetActive(false);shield[i].enabled=slow[i].enabled=haste[i].enabled=fan[i].enabled=dash[i].enabled=false;dashLife[i]=0;blinkPending[i]=false;for(int j=0;j<3;j++)if(ghosts[i,j])ghosts[i,j].gameObject.SetActive(false);}}
        void OnDestroy(){if(shieldMaterial)Destroy(shieldMaterial);if(glow)Destroy(glow);if(smoke)Destroy(smoke);if(impact)Destroy(impact);if(softTexture)Destroy(softTexture);if(ghostMeshes!=null)foreach(var mesh in ghostMeshes)if(mesh)Destroy(mesh);}
    }
}
