using System;
using System.IO;
using PharmaBrawl;
using UnityEditor;
using UnityEngine;
public static class ReferenceAbilityBuilder
{
    public static void FinalBuild(){Capture();Validate();MobileAbilityValidator.Validate();PaengCombatValidator.Validate();PaengQualityCapture.Before();PaengQualityCapture.After();ArenaMapBuilder.BuildWeb();}
    public static void BuildWeb(){Capture();PaengQualityCapture.Before();PaengQualityCapture.After();Import();Validate();PaengCombatValidator.Validate();PremiumCombatBuilder.BuildWeb();}
    public static void Capture(){Import();Validate();for(int hero=1;hero<10;hero++)for(int ability=1;ability<=2;ability++){
            UnityEditor.SceneManagement.EditorSceneManager.NewScene(UnityEditor.SceneManagement.NewSceneSetup.EmptyScene);
            var sim=Setup(hero);var actors=new Transform[8];foreach(var f in sim.fighters){var actor=new GameObject(f.data.displayName);actor.transform.position=new Vector3(f.position.x,0,f.position.y);actor.transform.rotation=Quaternion.LookRotation(new Vector3(f.aim.x,0,f.aim.y));actor.AddComponent<PharmacistModelRig>().Initialize(f.data);actors[f.id]=actor.transform;}
            var light=new GameObject("QA light").AddComponent<Light>();light.type=LightType.Directional;light.intensity=1.4f;light.transform.rotation=Quaternion.Euler(45,-30,0);RenderSettings.ambientLight=Color.white*.7f;
            var floor=GameObject.CreatePrimitive(PrimitiveType.Cube);floor.transform.position=new Vector3(3,-.3f,0);floor.transform.localScale=new Vector3(35,.5f,18);floor.GetComponent<Renderer>().sharedMaterial=new Material(Shader.Find("Standard")){color=new Color(.25f,.38f,.48f)};
            var camera=new GameObject("Actual 3D ability QA camera").AddComponent<Camera>();camera.orthographic=true;camera.orthographicSize=6;camera.transform.position=new Vector3(4,13,-13);camera.transform.LookAt(new Vector3(4,1,0));camera.backgroundColor=new Color(.05f,.08f,.12f);
            var fxRoot=new GameObject("Real pooled effects");var lightning=fxRoot.AddComponent<LightningAbilityView>();lightning.Initialize(sim);var laser=fxRoot.AddComponent<GoldenAbilityView>();laser.Initialize(sim);var reference=fxRoot.AddComponent<ReferenceAbilityView>();reference.Initialize(sim,actors);sim.Event+=e=>{lightning.Emit(e);laser.Emit(e);reference.Emit(e);if((e.type=="skill"||e.type=="ultimate"))actors[e.actor].GetComponent<PharmacistModelRig>().BeginAbility(e.type=="ultimate");};
            var p=sim.fighters[0];if(ability==1)sim.Skill(p);else{p.charge=4000;sim.Ultimate(p);}Tick(sim,.1f);
            foreach(var f in sim.fighters){actors[f.id].position=new Vector3(f.position.x,0,f.position.y);actors[f.id].GetComponent<PharmacistModelRig>().UpdatePose(.1f);}
            reference.Advance(.1f);lightning.Advance(.1f);laser.Advance(.1f);
            foreach(var robot in sim.robots)if(robot.active){var robotObject=new GameObject("Generated Tripo summoned robot");robotObject.transform.position=new Vector3(robot.position.x,0,robot.position.y);var drone=robotObject.AddComponent<PharmacyDroneView>();drone.Initialize();drone.Sync(sim,Array.IndexOf(sim.robots,robot),.3f);}
            foreach(var ps in fxRoot.GetComponentsInChildren<ParticleSystem>())if(ps.gameObject.activeInHierarchy)ps.Simulate(.22f,false,false);
            var target=new RenderTexture(1400,850,24);camera.targetTexture=target;camera.Render();RenderTexture.active=target;var pixels=new Texture2D(1400,850,TextureFormat.RGB24,false);pixels.ReadPixels(new Rect(0,0,1400,850),0,0);pixels.Apply();File.WriteAllBytes(Path.GetFullPath("../../outputs/reference-"+hero+"-"+ability+".png"),pixels.EncodeToPNG());RenderTexture.active=null;camera.targetTexture=null;UnityEngine.Object.DestroyImmediate(pixels);UnityEngine.Object.DestroyImmediate(target);
        }Debug.Log("REFERENCE_RENDER_CAPTURE_PASS 18 actual Unity skill/ultimate scenes");}
    public static void Import(){AssetDatabase.Refresh();foreach(string shader in new[]{"MedicalVFX","MedicalShield"}){string path="Assets/Resources/VFX/"+shader+".mat";if(!AssetDatabase.LoadAssetAtPath<Material>(path))AssetDatabase.CreateAsset(new Material(Shader.Find("Pharma/"+shader)),path);}var atlas=(TextureImporter)AssetImporter.GetAtPath("Assets/Resources/VFX/MedicalAtlas.png");atlas.maxTextureSize=1024;atlas.mipmapEnabled=false;atlas.alphaSource=TextureImporterAlphaSource.FromInput;atlas.wrapMode=TextureWrapMode.Clamp;atlas.SaveAndReimport();Directory.CreateDirectory("Assets/Resources/Robots");
        foreach(string name in new[]{"Support","Elite"}){
            string folder="Assets/Art/Robots/"+name;var importer=(ModelImporter)AssetImporter.GetAtPath(folder+"/model.fbx");importer.importAnimation=false;importer.importCameras=false;importer.importLights=false;importer.materialImportMode=ModelImporterMaterialImportMode.ImportStandard;importer.materialLocation=ModelImporterMaterialLocation.External;importer.SaveAndReimport();
            Directory.CreateDirectory(folder+"/Textures");if(Directory.GetFiles(folder+"/Textures","*.png").Length==0)importer.ExtractTextures(folder+"/Textures");AssetDatabase.Refresh();foreach(string file in Directory.GetFiles(folder+"/Textures")){var ti=AssetImporter.GetAtPath(file.Replace('\\','/')) as TextureImporter;if(ti){ti.maxTextureSize=512;ti.textureCompression=TextureImporterCompression.Compressed;ti.SaveAndReimport();}}
            importer.SearchAndRemapMaterials(ModelImporterMaterialName.BasedOnMaterialName,ModelImporterMaterialSearch.Local);importer.SaveAndReimport();var model=UnityEngine.Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(folder+"/model.fbx"));
            foreach(var renderer in model.GetComponentsInChildren<Renderer>())foreach(var material in renderer.sharedMaterials)if(material){material.shader=Shader.Find("Standard");material.SetTexture("_BumpMap",null);material.SetTexture("_MetallicGlossMap",null);material.DisableKeyword("_NORMALMAP");material.DisableKeyword("_METALLICGLOSSMAP");material.SetFloat("_Metallic",0);material.SetFloat("_Glossiness",.25f);EditorUtility.SetDirty(material);}
            PrefabUtility.SaveAsPrefabAsset(model,"Assets/Resources/Robots/"+name+".prefab");UnityEngine.Object.DestroyImmediate(model);
        }
        // Reuse already generated Tripo medical guns matching the reference families.
        Directory.CreateDirectory("Assets/Art/ReferenceWeapons");
        int[] sources={4,5,3,0,2,6,0,2,9};
        for(int hero=1;hero<10;hero++){
            string key=sources[hero-1].ToString("00");string folder="Assets/Art/ReferenceWeapons/"+hero.ToString("00");Directory.CreateDirectory(folder);
            var instance=UnityEngine.Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Art/Weapons/"+key+"/model.fbx"));string matPath=folder+"/Weapon.mat";var material=AssetDatabase.LoadAssetAtPath<Material>(matPath);if(!material){material=new Material(Shader.Find("Standard"));AssetDatabase.CreateAsset(material,matPath);}material.shader=Shader.Find("Pharma/MedicalPalette");material.mainTexture=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/Weapons/"+key+"/Textures/tripo_model_basecolor.JPEG");material.SetFloat("_Metallic",0);material.SetFloat("_Glossiness",.25f);foreach(var renderer in instance.GetComponentsInChildren<Renderer>())renderer.sharedMaterial=material;var prefab=PrefabUtility.SaveAsPrefabAsset(instance,folder+"/Weapon.prefab");UnityEngine.Object.DestroyImmediate(instance);
            foreach(var data in Resources.LoadAll<CharacterDefinition>("Characters"))if((int)data.kind==hero){data.weaponPrefab=prefab;material.color=data.color;EditorUtility.SetDirty(material);EditorUtility.SetDirty(data);}
        }
        AssetDatabase.SaveAssets();
    }
    static void Require(bool condition,string message){if(!condition)throw new Exception("Reference ability validation: "+message);}
    static CharacterDefinition[] Roster(){var r=Resources.LoadAll<CharacterDefinition>("Characters");Array.Sort(r,(a,b)=>a.kind.CompareTo(b.kind));return r;}
    static ArenaSimulation Setup(int hero,int teamSize=4){var picks=new int[teamSize*2];for(int i=0;i<picks.Length;i++)picks[i]=hero;var sim=new ArenaSimulation(Roster(),hero,73,0,teamSize,picks);sim.covers.Clear();for(int i=0;i<sim.fighters.Length;i++){sim.fighters[i].position=new Vector2(i<teamSize?-15-i:2+(i-teamSize)*2,0);sim.fighters[i].human=true;}sim.fighters[0].position=Vector2.zero;sim.fighters[0].aim=Vector2.right;sim.fighters[0].aimDistance=2;return sim;}
    static void Tick(ArenaSimulation sim,float dt){var inputs=new ArenaSimulation.HumanInput[sim.fighters.Length];for(int i=0;i<inputs.Length;i++)inputs[i].human=true;sim.TickNetwork(dt,inputs);}
    public static void Validate(){
        var sim=Setup(1);var lightningRoot=new GameObject("Lightning QA");var lightning=lightningRoot.AddComponent<LightningAbilityView>();lightning.Initialize(sim);sim.Event+=lightning.Emit;sim.Skill(sim.fighters[0]);Require(sim.fighters[4].damageTaken==500&&sim.fighters[5].damageTaken==500&&sim.fighters[6].damageTaken==0,"skill targets exactly two for 500");Require(lightning.LastFrom.x==2&&lightning.LastTo.x==4,"second arc starts at first victim");Require(sim.fighters[0].skillTimer==6,"skill cooldown");sim.Skill(sim.fighters[0]);Require(sim.fighters[4].damageTaken==500,"cooldown prevents repeats");lightning.Advance(1);Require(lightning.ActiveArcs==0,"lightning expiry");sim.Ultimate(sim.fighters[0]);Require(sim.ultimatesUsed==0,"charge gate");sim.fighters[0].charge=4000;sim.Ultimate(sim.fighters[0]);Require(lightning.ActiveArcs==4,"ultimate four actual opponents");Require(sim.fighters[7].damageTaken==850,"ultimate 850 each");lightning.Clear();lightning.Advance(1);Require(lightning.ActiveArcs==0,"lightning cleanup");UnityEngine.Object.DestroyImmediate(lightningRoot);
        sim=Setup(2);sim.Skill(sim.fighters[0]);Require(sim.fighters[0].empowered,"piercing ready");sim.Attack(sim.fighters[0]);Require(!sim.fighters[0].empowered&&Array.Find(sim.shots,s=>s.active).piercing,"next shot consumes piercing");for(int i=0;i<30;i++)Tick(sim,1f/60);Require(sim.fighters[4].damageTaken==780&&sim.fighters[5].damageTaken==780,"piercing multiple enemies once");
        sim=Setup(2);sim.fighters[5].position=new Vector2(4,.79f);sim.fighters[6].position=new Vector2(6,.81f);var root=new GameObject("Golden beam QA");var laser=root.AddComponent<GoldenAbilityView>();laser.Initialize(sim);sim.Event+=laser.Emit;sim.fighters[0].charge=4000;sim.Ultimate(sim.fighters[0]);Require(sim.fighters[4].damageTaken==1900&&sim.fighters[5].damageTaken==1900&&sim.fighters[6].damageTaken==0,"exact .8 half width laser");Require(laser.LastLength==35&&laser.LastHalfWidth==.8f,"35 distance marker width matches");laser.Advance(1);Require(laser.ActiveBeams==0,"laser expiry");UnityEngine.Object.DestroyImmediate(root);
        sim=Setup(3);sim.Skill(sim.fighters[0]);sim.Damage(4,0,100);Require(sim.fighters[0].damageTaken==45&&sim.fighters[0].shield==4,"shield reduces 55 percent for four seconds");sim=Setup(4);sim.Skill(sim.fighters[0]);sim.Attack(sim.fighters[0]);Require(Mathf.Abs(sim.fighters[0].attackTimer-sim.fighters[0].data.attackInterval*.45f)<.001f,"haste interval");sim=Setup(4);sim.fighters[0].charge=4000;sim.Ultimate(sim.fighters[0]);Require(sim.shotsFired==13&&sim.fighters[0].rapidRemaining==3.5f,"13 initial barrage and 3.5 second auto fire");
        sim=Setup(5);sim.Skill(sim.fighters[0]);var zone=Array.Find(sim.zones,z=>z.active);Require(zone.kind==1&&zone.remaining==5&&zone.radius==2&&zone.damage==150,"artillery skill zone");sim=Setup(5);sim.fighters[0].charge=4000;sim.Ultimate(sim.fighters[0]);Require(Array.FindAll(sim.zones,z=>z.active).Length==7,"seven bombardments");
        sim=Setup(6);sim.Skill(sim.fighters[0]);Require(sim.fighters[0].position.x==4,"four distance blink");sim=Setup(6);sim.fighters[0].charge=4000;sim.Ultimate(sim.fighters[0]);Require(Vector2.Distance(sim.fighters[0].position,sim.fighters[4].position-sim.fighters[4].aim*1.1f)<.001f&&sim.fighters[4].damageTaken==1800,"behind-target blink and original 1800");
        sim=Setup(7);sim.Skill(sim.fighters[0]);var robot=Array.Find(sim.robots,r=>r.active);Require(!robot.elite&&robot.remaining==10,"support lifetime");sim.fighters[0].charge=4000;sim.Ultimate(sim.fighters[0]);Require(Array.Find(sim.robots,r=>r.active&&r.elite).remaining==15,"elite lifetime");for(int i=0;i<25;i++)Tick(sim,1f/60);Require(sim.fighters[4].damageTaken>0||Array.Exists(sim.shots,s=>s.active&&(s.damage==160||s.damage==240)),"robot real projectiles");root=new GameObject("Tripo robot QA");var drone=root.AddComponent<PharmacyDroneView>();drone.Initialize();Require(drone.HasTripoModels,"both independent Tripo prefabs");UnityEngine.Object.DestroyImmediate(root);
        sim=Setup(8);sim.Skill(sim.fighters[0]);sim.Attack(sim.fighters[0]);Require(sim.shotsFired==5&&Array.Find(sim.shots,s=>s.active).remaining==sim.fighters[0].data.range*1.4f,"five empowered spread shots and 40 percent range");sim=Setup(8);sim.fighters[0].charge=4000;sim.Ultimate(sim.fighters[0]);Require(sim.shotsFired==17&&Array.Find(sim.shots,s=>s.active).damage==300,"17 shots 300 each");
        sim=Setup(9);sim.Skill(sim.fighters[0]);zone=Array.Find(sim.zones,z=>z.active);Require(zone.kind==2&&zone.remaining==4&&zone.radius==2.5f&&zone.damage==170,"poison skill values");root=new GameObject("Gas particle QA");var view=root.AddComponent<ReferenceAbilityView>();view.Initialize(sim);view.Advance(0);Require(view.ActiveZones==1,"gas actual zone");foreach(var ps in root.GetComponentsInChildren<ParticleSystem>())if(ps.name=="Expanding purple gas"&&ps.gameObject.activeInHierarchy){Require(ps.main.loop&&ps.main.maxParticles==24,"expanding pooled particles limited");Require(ps.colorOverLifetime.enabled&&ps.sizeOverLifetime.enabled,"gas expands and fades");}view.Clear();view.Advance(1);Require(view.ActiveZones==0,"gas cleanup");UnityEngine.Object.DestroyImmediate(root);
        sim=Setup(9);sim.fighters[0].charge=4000;sim.Ultimate(sim.fighters[0]);zone=Array.Find(sim.zones,z=>z.active);Require(zone.remaining==5&&zone.radius==4.5f&&zone.damage==220,"ultimate poison values");
        Debug.Log("REFERENCE_ABILITIES_PASS nine characters: ordered chain, piercing, exact beam, shield, haste, artillery, blink, Tripo robots, fan and particle gas; original combat unchanged");
    }
}

